### ISSUE TITLE
Handle country/regions with same names

### ISSUE THREAD

**Issue by planemad** [mapbox/osm-coverage#3]
While processing [region](https://github.com/mapbox/osm-coverage/tree/regions) coverage, noticed that the code does not handle duplicate names and the numbers are overwritten over a state with the same name of a different country, eg. Punjab in Pakistan and India.

**Comment by tcql** [comment]
@planemad  I think you would want to include country + region name in the results. So for example, on the region branch, you'd need to do: 

```
var country = findCountry(tile, countryIndex);
var state = findState(tile, stateIndex);

var resultClasses = {};
resultClasses[country] = {};
resultClasses[country][state] = {
  "classified": {},
  "raw": {}
};

// ....

handleRoad(ft.toGeoJSON(tile[0], tile[1], tile[2]), bbox, resultClasses[country][state]);
```

This will nest the state/regions under the countries, preventing collision.
