### ISSUE TITLE
npm error - pm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Cloning into bare repository '/home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264'...

### ISSUE THREAD

**Issue by nikhil271995** [mapbox/osm-coverage#8]
LRN package.json osm-coverage@1.0.0 No repository field.
npm ERR! git rev-list -n1 bbox: fatal: ambiguous argument 'bbox': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 bbox: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 bbox: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 bbox: 
npm WARN deprecated turf-line-distance@1.0.2: Turf packages are now namespaced: please use @turf/line-distance instead
npm ERR! git rev-list -n1 bbox: fatal: ambiguous argument 'bbox': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 bbox: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 bbox: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 bbox: 
npm WARN deprecated tilebelt@1.0.1: This module is now under the @mapbox namespace: install @mapbox/tilebelt instead
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Cloning into bare repository '/home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264'...
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Permission denied (publickey).
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: 
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/anv13/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/which-polygon.git /home/anv13/.npm/_git-remotes/git-github-com-mapbox-which-polygon-git-2014c264: and the repository exists.
npm WARN deprecated tile-reduce@3.1.1: This module is now under the @mapbox namespace: install @mapbox/tile-reduce instead

**Comment by miles-dev** [comment]
@nikhil271995 - This has been fixed. It was an issue with the package.json references a no longer existing branch.

**Comment by RaviBalajiKannan** [comment]
How can i resolve this issue?
